[package]
name = "phantom_world"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.12.1", features = ["derive"] }
phantom_dependencies = { path = "../phantom_dependencies" }
thiserror = "1.0.32"
