[package]
name = "phantom_render"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.17"
phantom_config = { path = "../phantom_config" }
phantom_gui = { path = "../phantom_gui" }
phantom_world = { path = "../phantom_world" }
raw-window-handle = "0.5.0"
thiserror = "1.0.38"
