[package]
name = "phantom_app"
version = "0.1.0"
edition = "2021"

[dependencies]
phantom_dependencies = { path = "../phantom_dependencies" }
phantom_render = { path = "../phantom_render" }
thiserror = "1.0.31"
