[package]
name = "phantom_app"
version = "0.1.0"
edition = "2021"

[dependencies]
phantom_config = { path = "../phantom_config" }
phantom_dependencies = { path = "../phantom_dependencies" }
phantom_gui = { path = "../phantom_gui" }
phantom_render = { path = "../phantom_render" }
phantom_world = { path = "../phantom_world" }
thiserror = "1.0.32"
