on: 
  pull_request:
    branches: [main]

name: Phantom CI

jobs:
  check:
    name: Lint, Build, Test
    runs-on: ubuntu-latest
    steps:
      - name: Install libudev-dev
        run: sudo apt-get install -y libudev-dev

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Lint (clippy)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: Lint (rustfmt)
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Check (cargo check)
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Test (cargo test)
        uses: actions-rs/cargo@v1
        with:
          command: test

