name: Phantom CI

on:
  push:
    branches: [main]

jobs:
  build-engine:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    name: Build and test phantom on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install -y libudev-dev libasound2-dev libatk1.0-dev libclang-dev libgtk-3-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2

      - name: Show versions
        run: |
          rustc --version
          cargo fmt -- --version
          cargo clippy -- --version

      - name: Check for errors
        run: cargo check --all --tests

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Lint
        run: cargo clippy --all --tests -- -D warnings

      - name: Test
        run: cargo test --all -- --nocapture
        env:
          RUST_LOG: debug
